//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryImage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.60")]
        public decimal _appVersion {
            get {
                return ((decimal)(this["_appVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.60 BETA")]
        public string _diVersion {
            get {
                return ((string)(this["_diVersion"]));
            }
            set {
                this["_diVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DirectoryImage is a small application to organize your data. Is free of charge an" +
            "d was developed by a student at University of Havana. That\'s me. Thanks for supp" +
            "ort my idea and write me to express any related opinion.")]
        public string _workPath {
            get {
                return ((string)(this["_workPath"]));
            }
            set {
                this["_workPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("krlostoledo@gmail.com")]
        public string _emailAddress {
            get {
                return ((string)(this["_emailAddress"]));
            }
            set {
                this["_emailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string _proyectoName {
            get {
                return ((string)(this["_proyectoName"]));
            }
            set {
                this["_proyectoName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11-21-2015")]
        public string _fechaCompilation {
            get {
                return ((string)(this["_fechaCompilation"]));
            }
            set {
                this["_fechaCompilation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:</string>\r\n  <string>D:</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _MostUsedPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_MostUsedPaths"]));
            }
            set {
                this["_MostUsedPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DirectoryImage v0.60")]
        public string _Name {
            get {
                return ((string)(this["_Name"]));
            }
            set {
                this["_Name"] = value;
            }
        }
    }
}
